"""
A list of the City of Minneapolis boards & commissions, taken from
http://www.ci.minneapolis.mn.us/boards-and-commissions/
"""

boards = (
    "Guest",
    "Above the Falls Citizen Advisory Committee",
    "Airports Commission, Metropolitan (MAC)",
    "Animal Care and Control Advisory Board",
    "Arts Commission, Minneapolis",
    "Bassett Creek Watershed Management Commission",
    "Bloomington-Lake Special Service District Board",
    "Capital Long Range Improvements Committee (CLIC)",
    "Central Avenue Special Service District Advisory Board",
    "Charter Commission",
    "Chicago Avenue Special Service District Advisory Board",
    "Chicago-Lake Special Service District Advisory Board",
    "Citizen Environmental Advisory Committee (CEAC)",
    "Civil Rights Commission, Minneapolis",
    "Civil Service Commission",
    "Civilian Police Review Authority",
    "Complete Count Committee (2010 Census)",
    "Dinkytown Special Service District Advisory Board",
    "Disabilities, Minneapolis Advisory Committee on People With",
    "Downtown Skyway Advisory Committee",
    "Economic Development Company, Minneapolis (MEDC)",
    "Estimate and Taxation, Board of",
    "Ethical Practices Board",
    "Family Housing Fund (McKnight), Minneapolis/St. Paul",
    "Fire Code Board of Appeals",
    "Forty Third Street West and Upton Avenue South Special Service District",
    "Franklin Avenue East Special Service District Advisory Board",
    "Heritage Preservation Commission",
    "Hennepin Theatre District Special Service District Advisory Board",
    "Housing Board of Appeals",
    "Latino Community Advisory Committee to the Mayor and the City Council",
    "Linden Hills Advisory Board",
    "Minneapolis Tree Advisory Commission",
    "Minneapolis Workforce Council",
    "Minnehaha Creek Watershed District Board",
    "Mississippi Watershed Management Organization",
    "Municipal Building Commission",
    "Neighborhood Revitalization Program (NRP) Policy Board",
    "Neighborhood and Community Engagement Commission",
    "Nicollet Avenue South Special Service District",
    "Nicollet Mall South Special Service District",
    "Park and Recreation Board of Commissioners, Minneapolis",
    "Pedestrian Advisory Committee",
    "Planning Commission",
    "Public Health Advisory Committee",
    "Public Housing Authority, Minneapolis",
    "School Board, Minneapolis",
    "Senior Citizen Advisory Committee to the Mayor and City Council",
    "Shingle Creek Watershed Management Commission",
    "South Hennepin Avenue Special Service District Advisory Board",
    "Sports Facilities Commission, Metropolitan",
    "Stadium Village Special Service District Advisory Board",
    "Telecommunications Network (MTN), Minneapolis",
    "Truth in Sale of Housing Board of Appeals",
    "Uptown Special Service District Advisory Committee",
    "Workforce Council, Minneapolis",
    "Youth Coordinating Board",
    "Youth Violence Executive Committee",
    "Zoning Board of Adjustment",
)

