#!/usr/bin/env python2.4

from google.appengine.ext import db


class Completion(db.Model):
    """This class models an object for recording a learner's completion of the
    ethics training."""
    name = db.StringProperty(verbose_name='Learner Name')
    board = db.StringProperty(verbose_name='Learner Board or Commission')
    date = db.DateTimeProperty(verbose_name='Completion Timestamp',
        auto_now_add=True)


class Scenario(db.Model):
    """This class models a scenario, which equates to a question."""

    name = db.StringProperty(required=True)
    scenario = db.TextProperty(required=True)
    question = db.TextProperty(required=True)
    prompt = db.StringProperty()

    # additional Scenario property 'answer_set' is autogenerated by the
    # ReferenceProperty in the Answer object...

    def as_dict(self):
        return dict(name=self.name,
                    scenario=self.scenario,
                    question=self.question,
                    prompt=self.prompt)


class Answer(db.Model):
    """This class models an answer."""

    scenario = db.ReferenceProperty(Scenario)
    answer = db.StringProperty()
    is_correct = db.BooleanProperty()
    response = db.TextProperty()

    def as_dict(self):
        return dict(name=self.key().name(),
                    scenario=self.scenario,
                    answer=self.answer,
                    is_correct=self.is_correct,
                    response=self.response)
