# Copyright 2012 John J. Trammell.
#
# This file is part of the Mpls-ethics software package.  Mpls-ethics
# is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# Mpls-ethics is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Mpls-ethics.  If not, see <http://www.gnu.org/licenses/>.

from google.appengine.ext import db


class Completion(db.Model):
    """This class models an object for recording a learner's completion of the
    ethics training."""
    name = db.StringProperty(verbose_name='Learner Name')
    board = db.StringProperty(verbose_name='Learner Board or Commission')
    date = db.DateTimeProperty(verbose_name='Completion Timestamp',
        auto_now_add=True)


class Scenario(db.Model):
    """This class models a scenario, which equates to a question."""

    name = db.StringProperty(required=True)
    scenario = db.TextProperty(required=True)
    question = db.TextProperty(required=True)
    prompt = db.StringProperty()

    # additional Scenario property 'answer_set' is autogenerated by the
    # ReferenceProperty in the Answer object...

    def as_dict(self):
        return dict(name=self.name,
                    scenario=self.scenario,
                    question=self.question,
                    prompt=self.prompt)


class Answer(db.Model):
    """This class models an answer."""

    scenario = db.ReferenceProperty(Scenario)
    answer = db.StringProperty()
    is_correct = db.BooleanProperty()
    response = db.TextProperty()

    def as_dict(self):
        return dict(name=self.key().name(),
                    scenario=self.scenario,
                    answer=self.answer,
                    is_correct=self.is_correct,
                    response=self.response)
