application: 'mpls-ethics'
version: 3
runtime: python
api_version: 1
handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /.*
  script: met/app.py

